[build]
  command = "npm --prefix emergix run build --workspace=web"
  publish = "emergix/apps/web/dist"
  functions = "emergix/apps/web/netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
